prgrms-web-devcourse-final-project/WEB5_6_88hage_BE

- src/main/java/com/grepp/funfun/app/controller/api/group/GroupApiController.java
- src/main/java/com/grepp/funfun/app/controller/api/group/payload/GroupRequest.java
- src/main/java/com/grepp/funfun/app/controller/api/participant/ParticipantApiController.java
- src/main/java/com/grepp/funfun/app/controller/web/group/GroupController.java
- src/main/java/com/grepp/funfun/app/model/chat/entity/ChatRoom.java
- src/main/java/com/grepp/funfun/app/model/group/dto/GroupDTO.java
- src/main/java/com/grepp/funfun/app/model/group/entity/Group.java
- src/main/java/com/grepp/funfun/app/model/group/repository/GroupRepository.java
- src/main/java/com/grepp/funfun/app/model/group/repository/GroupRepositoryCustom.java
- src/main/java/com/grepp/funfun/app/model/group/repository/GroupRepositoryCustomImpl.java
- src/main/java/com/grepp/funfun/app/model/group/service/GroupService.java
- src/main/java/com/grepp/funfun/app/model/participant/code/ParticipantRole.java
- src/main/java/com/grepp/funfun/app/model/participant/entity/Participant.java
- src/main/java/com/grepp/funfun/app/model/participant/repository/ParticipantRepository.java
- src/main/java/com/grepp/funfun/app/model/participant/repository/ParticipantRepositoryCustom.java
- src/main/java/com/grepp/funfun/app/model/participant/repository/ParticipantRepositoryCustomImpl.java
- src/main/java/com/grepp/funfun/app/model/participant/service/ParticipantService.java
- src/main/java/com/grepp/funfun/app/model/user/repository/UserRepository.java
- src/main/resources/messages.properties
- src/main/resources/templates/group/add.html
**📌 과제 설명**
- 모임 기능 
- 모임 생성
- 채팅방 생성
- 참여 신청
- 참여 승인
**👩‍💻 요구 사항과 구현 내용**
1. 모임 기능
- 모임 관련된 기능 구현
2. 모임 생성
- 모임을 생성 -> 참여자 테이블에 리더로 저장되도록 구현
- 추가적으로 모임 생성 시 모임 전용 채팅방 생성
3. 참여 신청
- 사용자가 참여 신청 -> PENDING 상태로 참여자 테이블 저장
4. 참여 승인
- PENDING 이고 True 상태인 사용자를 조회하는 기능 추가
- 조회 후 일괄 수락을 위해 선택한 사용자 이메일을 List 로 받아서 반복문을 통해 APPROVE 로 변경
- 최대 인원을 넘지 못하게 검증
- 현재 인원이 최대 인원과 같아지면 모임 상태 FULL 로 변경
> feat: 모임 기능

- src/main/java/com/grepp/funfun/app/controller/api/social/FollowApiController.java
- src/main/java/com/grepp/funfun/app/controller/api/social/payload/FollowsResponse.java
- src/main/java/com/grepp/funfun/app/model/social/repository/FollowRepository.java
- src/main/java/com/grepp/funfun/app/model/social/repository/FollowRepositoryCustom.java
- src/main/java/com/grepp/funfun/app/model/social/repository/FollowRepositoryCustomImpl.java
- src/main/java/com/grepp/funfun/app/model/social/service/FollowService.java
팔로우 기능 구현했습니다.
* 팔로우
* 자기 자신은 팔로우 불가
* 이미 팔로우한 사람인지 검증 
* 언팔로우
* 팔로우 관계인지 검증 
* 팔로워 조회
* 이메일, 닉네임, 이미지 url 응답
* 팔로잉 조회
* 이메일, 닉네임, 이미지 url 응답
* 팔로워 수 조회
* 팔로잉 수 조회
* 팔로우 여부 확인
> feat: 팔로우 기능 구현

- src/main/java/com/grepp/funfun/app/model/bookmark/service/ContentBookmarkService.java
- src/main/java/com/grepp/funfun/app/model/content/repository/ContentRepository.java
- src/main/java/com/grepp/funfun/app/model/content/repository/ContentRepositoryCustom.java
- src/main/java/com/grepp/funfun/app/model/content/repository/ContentRepositoryCustomImpl.java
- src/main/java/com/grepp/funfun/app/model/content/service/ContentService.java
- src/test/java/com/grepp/funfun/app/model/content/service/ContentServiceTest.java
- queryDSL로 repository 수정
- 테스트 코드 작성
> fix: repository 수정, 테스트 코드 작성

- src/main/java/com/grepp/funfun/app/controller/api/participant/payload/ParticipantResponse.java
- src/main/java/com/grepp/funfun/app/model/group/service/GroupService.java
- src/main/java/com/grepp/funfun/app/model/participant/repository/ParticipantRepository.java
- src/main/java/com/grepp/funfun/app/model/participant/repository/ParticipantRepositoryCustomImpl.java
- src/main/java/com/grepp/funfun/app/model/participant/service/ParticipantService.java
- src/test/java/com/grepp/funfun/app/model/group/service/GroupServiceTest.java
- src/test/java/com/grepp/funfun/app/model/integrate/UserParticipantIntegrateTest.java
- src/test/java/com/grepp/funfun/app/model/participant/service/ParticipantServiceTest.java
📌 과제 설명
feat: 테스트 코드
fix: 검증 및 reponse 수정
👩‍💻 요구 사항과 구현 내용
테스트 코드 작성
> feat: 테스트 코드

- src/main/java/com/grepp/funfun/app/domain/social/controller/FollowApiController.java
- src/main/java/com/grepp/funfun/app/domain/social/service/FollowService.java
- src/test/java/com/grepp/funfun/app/domain/social/service/FollowServiceTest.java
기존 팔로우 기능에서 팔로워 여부 확인 기능 추가 구현했습니다.
* 팔로워 여부 확인 기능
> feat: 팔로우 기능 추가 구현

- src/main/java/com/grepp/funfun/app/infra/auth/jwt/filter/LogoutFilter.java
- src/main/java/com/grepp/funfun/app/infra/auth/oauth2/OAuth2FailureHandler.java
- src/main/java/com/grepp/funfun/app/infra/auth/oauth2/OAuth2SuccessHandler.java
OAuth2 로직, 경로 수정
* front 경로 반영될 수 있게 수정했습니다.
* OAuth2 유저의 취향을 가져오는 과정에서 지연 로딩 오류를 수정했습니다.
* Role이 USER_GUEST일 때, 쿠키가 제대로 저장되지 않던 현상을 수정했습니다.
> fix: OAuth2 수정

- src/main/java/com/grepp/funfun/app/domain/user/dto/UserDTO.java
- src/main/java/com/grepp/funfun/app/domain/user/dto/payload/SignupRequest.java
- src/main/java/com/grepp/funfun/app/domain/user/entity/User.java
- src/main/java/com/grepp/funfun/app/domain/user/service/UserService.java
- src/main/resources/templates/user/list.html
회원가입 시 위경도 정보 받도록 수정했습니다.
User 엔티티에 위경도 필드 추가로 테이블 update 필요합니다.
> fix: 회원가입 시 위경도 받기

- src/main/java/com/grepp/funfun/app/domain/calendar/service/CalendarService.java
- src/main/java/com/grepp/funfun/app/domain/content/entity/Content.java
- src/main/java/com/grepp/funfun/app/domain/report/controller/ReportApiController.java
- src/main/java/com/grepp/funfun/app/domain/report/dto/ReportDTO.java
- src/main/java/com/grepp/funfun/app/domain/report/dto/payload/ReportRequest.java
- src/main/java/com/grepp/funfun/app/domain/report/entity/Report.java
- src/main/java/com/grepp/funfun/app/domain/report/service/ReportService.java
- src/main/java/com/grepp/funfun/app/domain/report/vo/ReportType.java
- src/main/resources/data.sql
- src/main/resources/templates/report/list.html
신고 기능 구현했습니다.
* 신고 기능
* 자기 자신은 신고할 수 없습니다.
* 쪽지 기능 삭제로 ReportType에서 MESSAGE 삭제했습니다.
* Report 필드 변경 : String contentId -> Long targetId
* 신고 대상 리소스를 검증합니다.
* POST 타입 : 신고 대상자가 작성한 모임 게시글이 맞는지 확인
* CHAT 타입 : 신고 대상자가 작성한 채팅이 맞는지 확인  
* 캘린더 등록/취소 시 컨텐츠 즐겨찾기 수 카운트
* 기존 Content 엔티티의 bookmarkCount를 사용했습니다. 
* 더미데이터 추가
* 유저 정보, 취향, 캘린더, 팔로우, 신고  
Report 엔티티 수정으로 테이블 create 필요합니다.
> feat: 신고 기능 구현

- src/main/java/com/grepp/funfun/app/domain/calendar/controller/CalendarApiController.java
- src/main/java/com/grepp/funfun/app/domain/calendar/dto/payload/CalendarContentResponse.java
- src/main/java/com/grepp/funfun/app/domain/calendar/repository/CalendarRepository.java
- src/main/java/com/grepp/funfun/app/domain/calendar/repository/CalendarRepositoryCustom.java
- src/main/java/com/grepp/funfun/app/domain/calendar/repository/CalendarRepositoryCustomImpl.java
- src/main/java/com/grepp/funfun/app/domain/calendar/service/CalendarService.java
- src/main/java/com/grepp/funfun/app/domain/contact/controller/ContactApiController.java
- src/main/java/com/grepp/funfun/app/domain/contact/dto/ContactDTO.java
- src/main/java/com/grepp/funfun/app/domain/contact/dto/payload/ContactDetailResponse.java
- src/main/java/com/grepp/funfun/app/domain/contact/dto/payload/ContactRequest.java
- src/main/java/com/grepp/funfun/app/domain/contact/dto/payload/ContactResponse.java
- src/main/java/com/grepp/funfun/app/domain/contact/entity/Contact.java
- src/main/java/com/grepp/funfun/app/domain/contact/entity/ContactImage.java
- src/main/java/com/grepp/funfun/app/domain/contact/repository/ContactRepository.java
- src/main/java/com/grepp/funfun/app/domain/contact/repository/ContactRepositoryCustom.java
- src/main/java/com/grepp/funfun/app/domain/contact/repository/ContactRepositoryCustomImpl.java
- src/main/java/com/grepp/funfun/app/domain/contact/service/ContactService.java
- src/main/java/com/grepp/funfun/app/domain/contact/vo/ContactCategory.java
- src/main/java/com/grepp/funfun/app/domain/s3/service/S3FileService.java
- src/main/java/com/grepp/funfun/app/domain/user/controller/UserInfoApiController.java
- src/main/java/com/grepp/funfun/app/infra/response/ResponseCode.java
- src/main/resources/data.sql
- src/main/resources/templates/contact/list.html
문의 기능 구현했습니다.
* 다중 파일 업로드 기능 구현
* 문의 작성 기능
* 이미지 최대 3MB, 한 번에 5개까지 업로드 가능
* 문의 수정 기능
* 답변 완료된 모임은 수정할 수 없습니다.
* 문의 삭제(비활성화) 기능
* 문의 상세 조회 기능
* 문의 목록 조회 기능
* Page 적용
* 문의 더미데이터 추가
* 일정 등록한 컨텐츠 조회 기능
* 컨텐츠 일정 등록 시 검증 추가
* 중복 등록 방지
Contact 엔티티 수정으로 테이블 create 필요합니다.
application.properties에 추가 사항있습니다.
```
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=15MB
```
> feat: 문의 기능 구현

- src/main/java/com/grepp/funfun/app/delete/controller/web/chat/ChatController.java
- src/main/java/com/grepp/funfun/app/domain/auth/controller/AuthApiController.java
- src/main/java/com/grepp/funfun/app/domain/chat/service/ChatRoomService.java
- src/main/java/com/grepp/funfun/app/domain/chat/service/ChatService.java
- src/main/java/com/grepp/funfun/app/domain/group/controller/GroupApiController.java
- src/main/java/com/grepp/funfun/app/domain/group/dto/payload/GroupListResponse.java
- src/main/java/com/grepp/funfun/app/domain/group/repository/GroupRepositoryCustomImpl.java
- src/main/java/com/grepp/funfun/app/domain/group/service/GroupService.java
- src/main/java/com/grepp/funfun/app/domain/participant/controller/ParticipantApiController.java
- src/main/java/com/grepp/funfun/app/domain/participant/service/ParticipantService.java
- src/main/java/com/grepp/funfun/app/infra/auth/jwt/TokenCookieFactory.java
- src/main/java/com/grepp/funfun/app/infra/auth/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/grepp/funfun/app/infra/auth/jwt/filter/LogoutFilter.java
- src/main/java/com/grepp/funfun/app/infra/config/RecommendationConfig.java
- src/main/java/com/grepp/funfun/app/infra/config/SwaggerConfig.java
- src/main/java/com/grepp/funfun/app/infra/config/WebConfig.java
- src/main/resources/templates/chat/personalChat.html
fix: 반환 타입 변경 및 조회 검색 코드 수정
모임 반환 타입 수정하고 조회 검색 코드 수정했습니다
https 로 배포하기 위해 수정 및 주석 제거 및 변경했습니다
> fix: 반환 타입 변경 및 조회 검색 코드 수정

- src/main/java/com/grepp/funfun/app/domain/group/controller/GroupHashtagApiController.java
- src/main/java/com/grepp/funfun/app/domain/group/repository/GroupRepositoryCustomImpl.java
- src/main/java/com/grepp/funfun/app/domain/group/service/GroupHashtagService.java
- src/main/java/com/grepp/funfun/app/infra/auth/jwt/TokenCookieFactory.java
- src/main/java/com/grepp/funfun/app/infra/config/SwaggerConfig.java
- src/main/resources/templates/chat/autoSearch.html
fix: 프론트 서버 경로 동기화
feat: 자동 완성 기능(with Redis)
서버 배포를 위한 프론트 서버 경로 동기화했습니다
자동 완성 기능 구현했습니다(redis 를 이용해서 set 방식)
ex) 대한민국 저장하면 대 대한 대한민 대한민국 저장되고 prefix를 인식하여 ex) 대 -> 대한민국 출력
테스트 페이지 -> localhost:8083/chats/autoSearch 에서 테스트 가능합니다
> feat: 자동 완성 기능

- src/main/java/com/grepp/funfun/app/domain/content/controller/ContentApiController.java
- src/main/java/com/grepp/funfun/app/domain/content/dto/payload/ContentFilterRequest.java
- src/main/java/com/grepp/funfun/app/domain/content/repository/ContentRepositoryCustom.java
- src/main/java/com/grepp/funfun/app/domain/content/repository/ContentRepositoryCustomImpl.java
- src/main/java/com/grepp/funfun/app/domain/content/service/ContentService.java
- 컨텐츠 정렬 수정
- 문제 : 컨트롤러에서 받은 pageable을 서비스에서 다시 재생성 함
- 해결 : 컨트롤러에서 정렬 처리
- 컨텐츠 조회 및 상세 조회 최종 정검 완료
> fix: content 정렬 수정

- src/main/java/com/grepp/funfun/app/domain/group/service/GroupService.java
- src/test/java/com/grepp/funfun/app/domain/group/service/ViewCountServiceTest.java
- src/test/java/com/grepp/funfun/app/domain/integrate/AutoCompleteIntegrateTest.java
- src/test/java/com/grepp/funfun/app/domain/integrate/ViewCountIntegrateTest.java
feat: 테스트 코드 (자동완성,조회수)
fix: redis key 저장 키 변경
redis 저장 경로를 통일 시켰습니다.
자동완성, 조회수 테스트 코드(단위,통합) 작성했습니다
> feat: 테스트 코드 (자동완성,조회수)

- src/main/java/com/grepp/funfun/app/domain/chat/controller/ChatApiController.java
- src/main/java/com/grepp/funfun/app/domain/chat/controller/ChatRoomApiController.java
- src/main/java/com/grepp/funfun/app/domain/group/controller/GroupApiController.java
- src/main/java/com/grepp/funfun/app/domain/group/service/GroupService.java
- src/main/java/com/grepp/funfun/app/domain/participant/controller/ParticipantApiController.java
- src/main/java/com/grepp/funfun/app/domain/participant/entity/Participant.java
- src/main/java/com/grepp/funfun/app/domain/participant/service/ParticipantService.java
- src/main/resources/data.sql
fix: 모임 더미 데이터 수정
refactor: 코드 리팩토링
fix: set 제거 및 메시지 추가
모임 데이터 수정하고, 코드 리팩토링 진행했습니다
참여 서비스 쪽에 set이 남아있는 것을 확인하고 수정했습니다(+예외 메시지 추가)
> refactor: 코드 리팩토링

- src/main/java/com/grepp/funfun/app/infra/config/WebSocketConfig.java
fix: 채팅을 위해 cors 설정 추가
웹 소켓 여는 과정에서 cors 설정 추가 했습니다
> fix: 채팅을 위해 cors 설정 추가

- src/main/java/com/grepp/funfun/app/domain/admin/controller/AdminNoticeApiController.java
- src/main/java/com/grepp/funfun/app/domain/admin/repository/AdminNoticeRepository.java
- src/main/java/com/grepp/funfun/app/domain/admin/service/AdminNoticeService.java
list 로 적용되었던 부분을 pageable을 적용했습니다.
repository 에 페이징 메서드를 추가하여 service와 controller에서도 pageable을 받을 수 있도록 수정했습니다.
> refactor: 요구사항에 따른 admin notice 페이징 메서드 추가

- src/main/java/com/grepp/funfun/app/domain/chat/dto/payload/ChatResponse.java
- src/main/java/com/grepp/funfun/app/domain/chat/entity/Chat.java
- src/main/java/com/grepp/funfun/app/domain/chat/service/ChatService.java
- src/main/java/com/grepp/funfun/app/domain/group/dto/payload/GroupMyResponse.java
- src/main/java/com/grepp/funfun/app/domain/group/service/GroupService.java
- src/main/resources/templates/chat/groupChat.html
fix: chat 반환 값에 사용자 이미지 추가
채팅 구현 과정에 필요한 사용자 이미지 추가했습니다.
> fix: chat 반환 값에 사용자 이미지 추가

- src/main/java/com/grepp/funfun/app/domain/content/controller/ContentApiController.java
- src/main/java/com/grepp/funfun/app/domain/content/dto/ContentDetailDTO.java
- src/main/java/com/grepp/funfun/app/domain/content/dto/ContentListDTO.java
- src/main/java/com/grepp/funfun/app/domain/content/dto/ContentSimpleDTO.java
- src/main/java/com/grepp/funfun/app/domain/content/dto/payload/ContentDetailResponse.java
- src/main/java/com/grepp/funfun/app/domain/content/service/ContentService.java
- src/main/java/com/grepp/funfun/app/domain/content/service/DataPipeline.java
- src/main/java/com/grepp/funfun/app/infra/config/ModelMapperConfig.java
- src/test/java/com/grepp/funfun/app/domain/content/service/DataPipelineTest.java
- src/test/java/com/grepp/funfun/app/domain/content/service/KakaoGeoServiceTest.java
- 테스트 코드 수정 및 추가
- DataPipeline 테스트 코드 수정
- KakaoGeoService 테스트 코드 추가
- contentDTO → contentDetailDTO, contentListDTO, contentSimpleDTO 분리
- 컨텐츠 디테일 관련 컨텐츠 노출 5 → 2개로 수정
> refactor: 테스트 코드, DTO 수정

- src/main/java/com/grepp/funfun/app/domain/group/controller/GroupHashtagApiController.java
- src/main/java/com/grepp/funfun/app/domain/group/dto/payload/GroupSimpleResponse.java
- src/main/java/com/grepp/funfun/app/domain/group/service/GroupHashtagService.java
- src/test/java/com/grepp/funfun/app/domain/integrate/AutoCompleteIntegrateTest.java
- src/test/java/com/grepp/funfun/app/domain/integrate/AutoCompleteWithZSetIntegrateTest.java
fix: 자동완성 이전 값 저장(수정 예정)
fix: 스웨거 설명 변경
chore: 프론트에서 필요한 데이터 값 추가
fix: 해시태그(set -> ZSet(=Sorted Set) 변경
프론트 쪽에서 필요한 데이터 값 추가했습니다
자동완성 : 기존의 Set 자료형은 많은 키가 저장되어 하나의 키로 메모리 효율성을 높이기 위해 
Set -> ZSet 으로 수정했습니다.
테스트 코드에 기존의 auto Complete 코드 넣었는데 원래 형태와 바뀐 형태를 비교하기 위해 일단 넣었습니다.
[수정 예정입니다!]
> fix: 해시태그(set -> ZSet(=Sorted Set) 변경

- src/main/java/com/grepp/funfun/app/domain/content/controller/ContentApiController.java
- src/main/java/com/grepp/funfun/app/domain/content/dto/ContentListDTO.java
- src/main/java/com/grepp/funfun/app/domain/content/service/ContentService.java
- src/test/java/com/grepp/funfun/app/domain/content/service/ContentServiceTest.java
refactor: authentication 객체 사용하여 접근 구분
fix: contentService 테스트코드 수정
- 컨텐츠 목록 조회 시 Authentication 기반 분기 처리 적용
- ContentServiceTest에서 로그인/비로그인 케이스 구분
> refactor: authentication 기반 분기 처리 적용

- src/main/java/com/grepp/funfun/app/domain/content/service/DataPipeline.java
> chore: 날짜 지정한 거 수정

- src/main/java/com/grepp/funfun/app/infra/config/security/SecurityConfig.java
Security 설정했습니다.
현재 가독성을 위해서 기능별로 분리해서 권한을 설정했습니다.
각자 맡은 부분 권한 설정 잘 됐는지 확인 한 번씩 부탁드립니다.
> feat: Security 설정

- src/main/java/com/grepp/funfun/app/domain/group/service/GroupService.java
- src/main/java/com/grepp/funfun/app/domain/participant/service/ParticipantService.java
모임 신청, 승인, 거절, 강퇴 시 알림이 생성되고 즉시 발송됩니다.
기존 notification create 를 사용하여 각 상황별 알림 메세지를 생성하도록 구현했습니다. 
추가로 모임이 완료된 경우에도 알림 로직을 추가했습니다. 이는 link 로 해당 모임 게시글로 이동하게 되어있지만 차후 수정 가능합니다.
> feat: 모임 신청, 승인, 거절, 강퇴, 완료에 대한 알림 로직 추가

- src/main/java/com/grepp/funfun/app/domain/auth/controller/AuthApiController.java
- src/main/java/com/grepp/funfun/app/infra/config/WebConfig.java
- src/main/java/com/grepp/funfun/app/infra/config/security/SecurityConfig.java
- src/main/resources/data.sql
fix: Security 수정
fix: WebConfig 수정
> fix: Security 수정
